### ISSUE TITLE
JSONObject parameter in processDocument

### ISSUE THREAD

**Issue by DraGengX** [veryfi/veryfi-java#31] opened 2023-01-27 18:55 UTC
I found a potential [misguide ](https://github.com/veryfi/veryfi-java/blob/fa86c048787d3d5a70622ea773df075e289106bd/README.md)in your readme about Java API. I have already sent an email to report this to support.
Your example allows the JSONObject to be null.
However, I actually tried this and got response:
`{"status": "fail", "error": "Malformed parameters", "details": [{"loc": ["__root__"], "msg": "One of ['file_data', 'file_url', 'file_urls', 'dictation', 'package_path'] must be supplied", "type": "value_error"}]}`
I have proved that it is caused by the JSONObject parameter. Because when I add one of those mentioned parameters, it showed a different error message and looks it has the file:
`{"status": "fail", "error": "Could not decode base64 encoded file, Incorrect padding"}`

So the forth parameter JSONObject CAN NOT  be null in my opinion.

**Comment by DraGengX** [comment] 2023-01-27 19:16
![image](https://user-images.githubusercontent.com/15659328/215176688-7f66cbc6-6713-43b9-9c81-19f43e00e25d.png)

![image](https://user-images.githubusercontent.com/15659328/215176550-b96cc553-40a9-49e7-a210-aac31259b649.png)
![image](https://user-images.githubusercontent.com/15659328/215176624-729ea16f-3769-4c91-b9cd-6ffcf01566b7.png)

**Comment by Kaevan89** [comment] 2023-01-27 21:52
Hi @DraGengX, in both cases you are doing things wrong.
In the first case, you are sending a wrong path, or maybe I am wrong, are you sure the right location is D:\TryVeryfi\steak.JPEG, and do you have the right permissions to access that location? In the picture, I saw steak.JPEG in another location.

In the second case, you are trying to hardcode file_data parameter, you can do it, but that is not the right way, to do it you need to send a file_name too, and send as data "D:\\TryVeryfi\\steak.JPEG" is not going to give you goods results, because file_data is an image encoded in base64.

And to answer your question, if you send an empty JSONObject or a null variable, you'll get the same results, so it's okay to allow sending that value as null.

**Comment by DraGengX** [comment] 2023-01-27 22:11
![image](https://user-images.githubusercontent.com/15659328/215214546-aa98cb71-d574-424b-8706-26d6a0316ac5.png)
You can see I put a file check before I call the client. The file is there.

**Comment by DraGengX** [comment] 2023-01-27 22:21
Let me try another picture (maybe not JPEG). I guess it is encoding.

**Comment by DraGengX** [comment] 2023-01-27 23:43
It seems that `ClassLoader.getSystemResourceAsStream` can't read the existing file.

**Comment by DraGengX** [comment] 2023-02-01 05:31
I found out. ClassLoader.getSystemResourceAsStream used in process_document in Java SDK only reads files in the resources folder. It doesn't work with absolute path while process_document in Python SDK will work with absolute  path. 

![image](https://user-images.githubusercontent.com/15659328/215959196-04fe0a01-f895-42b0-8bbb-dc837d1659d6.png)

**Comment by kevkon3** [comment] 2023-03-24 22:09
@Kaevan89 I am having the same issue. I have also determined the issue to be caused by how the Java and Kotlin libraries are trying to read the file (I found the issue in Kotlin and came to see if the same issue would be seen in Java).

Since ClassLoader.getSystemResourceAsStream is being used, the file MUST be in the resources directory for it to work properly. This would be fine for test cases that already have the files in the correct location, but is not adequate when files exist elsewhere on the filesystem.

Compare this to the C# library which provides methods for processing the file as a stream, a byte array, or as a file path (not resource): https://github.com/veryfi/veryfi-csharp/blob/master/src/libs/Veryfi/Veryfi.ProcessDocumentFile.cs

**Comment by kevkon3** [comment] 2023-03-24 22:57
> @Kaevan89 I am having the same issue. I have also determined the issue to be caused by how the Java and Kotlin libraries are trying to read the file (I found the issue in Kotlin and came to see if the same issue would be seen in Java).
> 
> Since `ClassLoader.getSystemResourceAsStream` is being used, the file MUST be in the resources directory for it to work properly. This would be fine for test cases that already have the files in the correct location, but is not adequate when files exist elsewhere on the filesystem.
> 
> Compare this to the C# library which provides methods for processing the file as a stream, a byte array, or as a file path (not resource): https://github.com/veryfi/veryfi-csharp/blob/master/src/libs/Veryfi/Veryfi.ProcessDocumentFile.cs

I was just able to confirm this locally by updating how the file is read. My fix is in kotlin, but easy enough to move over to java. I'm going to open up a kotlin issue and PR for this over there in that project.

**Closed** 2023-03-29 23:46 UTC
